name: Update Comitology RSS

on:
  schedule:
    - cron: "23 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync with main
        run: |
          git fetch origin main
          git reset --hard origin/main

      - name: Test Comitology API GET
        run: |
          curl -i \
            'https://ec.europa.eu/transparency/comitology-register/core/api/front/documents/search?page=0&size=10&sort=updateDate%2Cdesc' \
            -H 'Accept: application/json, text/plain, */*' \
            -H 'Language: en' \
            -H 'User-Agent: Mozilla/5.0'

      - name: Generate RSS
        run: |
          python scraper.py

      - name: Commit RSS feed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add comitology.xml

          if git diff --cached --quiet; then
            echo "No changes."
            exit 0
          fi

          git commit -m "Update Comitology RSS feed"
          git push origin main
